#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 [YEAR]"
    exit 1
fi

YEAR="$1"

if [ ! -d $YEAR ]; then
    echo "$YEAR doesn't exist"
    exit 2
fi

for i in {1..25}
do
    ./rmday $YEAR $i
done

rm -fr $YEAR
